### ISSUE TITLE
本地音频没法正确地发送

### ISSUE THREAD

**Issue by RF-Tar-Railt** [GraiaProject/Application#101]
**描述你遇到的问题:**
使用Voice().fromLocalFile(XXX)只能发送一个无法播放的语音消息

**代码**

    if msg.startswith("test_voice"):
        await app.sendGroupMessage(group, MessageChain.create([Voice().fromLocalFile(filepath="test_voice.mp3")]))

**控制台日志输出截图:**

Group(xxxxx) <- '[mirai:voice:47C6A2674AAE13BEEE68A2F6DDBE0455.amr]'

是不是缺失了什么信息？

**Comment by GreyElaina** [comment]
你去问 mirai-api-http 实现去吧.
