### ISSUE TITLE
安装完后无法运行

### ISSUE THREAD

**Issue by djkcyl** [GraiaProject/Application#102]
安装完后无法运行

![image](https://user-images.githubusercontent.com/59153990/111155844-f6c8a080-85cf-11eb-9c11-59f262d579aa.png)

**运行环境:**
 - 操作系统: centos7
 - `mirai-core` 版本: 当前最新版
 - `mirai-api-http` 版本: 当前最新版
 - `graia-application-mirai` 版本: 当前最新版
 - 是否出现在机器人长期运行后:

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/111156218-7191bb80-85d0-11eb-95bd-7e98918d1f29.png)
![image](https://user-images.githubusercontent.com/59153990/111156233-77879c80-85d0-11eb-9eb8-5df885ede794.png)
非graia程序可运行

**Comment by GreyElaina** [comment]
poetry又忘记修改了 下个版本和pydantic的问题一起修

其他问题记得开debug

**Comment by djkcyl** [comment]
当前解决办法：更换python3.9  pydantic降级至1.7

**Comment by TravellerXi** [comment]
same issue. 建议做下兼容适配。

**Comment by GreyElaina** [comment]
bcc@next 解决了该问题。
