### ISSUE TITLE
是否有定时事件的功能

### ISSUE THREAD

**Issue by Viottery** [GraiaProject/Application#11]
类似nonebot的schedule。有的话麻烦给一下修饰器调用方法或者其他调用方法
麻烦了，谢谢！

**Comment by GreyElaina** [comment]
暂时无, 不过你可以试试自己用 `loop.create_task` 方法把你的异步函数丢事件循环里面, 那样就相当于是类似后台任务一样了

**Comment by GreyElaina** [comment]
可能会出一个封装, 不过我不喜欢 APScheduler, 所以用法可能比较不同, 虽然设计上是有这个.

**Comment by Viottery** [comment]
> 暂时无, 不过你可以试试自己用 `loop.create_task` 方法把你的异步函数丢事件循环里面, 那样就相当于是类似后台任务一样了

好的 谢谢！
