### ISSUE TITLE
使用其他基于sq内核的机器人向小可发送消息时小可不回复

### ISSUE THREAD

**Issue by Eric-Joker** [GraiaProject/Application#124]
**描述你遇到的问题:**
私聊时机器人向小可发送~help，小可不回复，若打开聊天界面复制机器人发送的消息重新发送小可能回复

**复现步骤:**
该 BUG 会在进行以下操作后出现:
使用基于sq内核的机器人框架

希望加个开关，控制群聊中小可回复时的引用指令消息

**Comment by OasisAkari** [comment]
问题提错仓库

**Comment by GreyElaina** [comment]
"SQ 内核", "小可", "~help", 我寻思这啥啊
