### ISSUE TITLE
是否能同时连接多个 bot

### ISSUE THREAD

**Issue by songrk415** [GraiaProject/Application#13]
类似nonebot，能否一个程序同时连接多个机器人，然后在调用的时候用类似于 `bot_id` 的参数来区分，有的话请问具体应该怎么做，感谢。

**Comment by GreyElaina** [comment]
没有, 考虑到 mirai-console 未来的发展趋势, 我不会做这个功能

~~其实要做也简单, 使用监听器层面的参数解析器注入就可以了, 不过没必要~~

**Comment by songrk415** [comment]
不太清楚未来的发展趋势指的什么。我是想把我在nonebot上做的哔哩哔哩开播提醒和动态转发的机器人移植过来。因为一个QQ账号每天@全体有上限，同时B站api每分钟抓取次数少得可怜。为了节省api调用次数和服务器性能开支，我一直都是一个脚本连多个机器人在不同的群推送这样的形式。

对我来说最重要的两个功能就是 scheduler 和同时连多个bot。看到 #11 提到未来会有定时任务非常高兴，介于本人技术力低下，如果大佬不愿意做多连，我也只能用些非常简单粗暴的方法实现（一个bot负责获取，其他的转发它的消息……）

**Comment by GreyElaina** [comment]
> 看到 #11 提到未来会有定时任务非常高兴

你现在就可以实现:

``` python
@loop.create_task
async def always_running_fetch():
    if is_it_time():
        # 你的send.

app.launch_blocking()
```
