### ISSUE TITLE
无法检测到闪照

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Application#14]
**描述你遇到的问题:**

无法接收到闪照

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 接收闪照

**控制台日志输出截图:**

MessageChain显示
`__root__=[Source(id=11246, time=datetime.datetime(2020, 8, 5, 8, 38, 17, tzinfo=datetime.timezone.utc))]`
mirai端信息
` 16:38:17 [INFO] [BOT 1779803343] [测试(904763352)] ILS(1450069615) -> [mirai:source:11246,375979852][mirai:flash:{1457EE2F-7AEC-4DA8-D4EF-3CDE37F81146}.mirai]`
**运行环境:**
 - 操作系统: Windows 10 x64
 - `mirai-core` 版本: 1.1.3
 - `mirai-api-http` 版本:1.7.3
 - `graia-application-mirai` 版本: 0.1.1
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
[code](https://github.com/GraiaProject/Application/blob/master/src/graia/application/message/elements/internal.py#L240-L257)

问题已经定位.
