### ISSUE TITLE
通过http连接 提示404

### ISSUE THREAD

**Issue by LinHui88** [GraiaProject/Application#141]
**描述你遇到的问题:**

<img width="798" alt="8AEC180D-3AC4-47D2-A144-1A637C16DC30" src="https://user-images.githubusercontent.com/40729083/124214448-2ffc3080-db2d-11eb-9474-3f4e945b69a5.png">

**发生错误的代码**

**控制台日志输出截图:**

**运行环境:**
 - 操作系统: 
 - `mirai-core` 版本:2.7 
 - `mirai-api-http` 版本: 2.0.2
 - `graia-application-mirai` 版本:最新版本 
 - 是否出现在机器人长期运行后: 否 无法启动

**额外信息:**
已经更新http-api的setting.yml
<img width="397" alt="75CEB50E-4413-4422-903A-539E8F78A42A" src="https://user-images.githubusercontent.com/40729083/124214671-908b6d80-db2d-11eb-876e-9bcd7491d759.png">

**Comment by GreyElaina** [comment]
application 将于 `v0.20.x` 发布兼容 mirai-api-http v2 的版本。
~~前提是我 git clone 不失败。~~

**Comment by GreyElaina** [comment]
v0.20.0 大概还会兼容 bcc 的 Landmark#2 版本（v0.10.0）。
