### ISSUE TITLE
mcl登录成功后运行bot出现connect_info=Session( TypeError: __init__() got an unexpected keyword argument 'authKey'错误

### ISSUE THREAD

**Issue by De3mond** [GraiaProject/Application#147]
具体报错：
Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    connect_info=Session(
TypeError: __init__() got an unexpected keyword argument 'authKey'

**Comment by karakoo** [comment]
新版graia还没有适配mah 2.x

以下版本是可以用的：
- graia用0.19.2
- broadcast用0.8.11
- mah用1.12.0
