### ISSUE TITLE
提示  metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by LinHui88** [GraiaProject/Application#148]
**描述你遇到的问题:**
提示 metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. ... 本来正常运行 然后手抖又安了一下scheduler
2. ...

**发生错误的代码**

![image](https://user-images.githubusercontent.com/40729083/125567246-077281d2-a061-42f9-93f7-4c0693ebbeb7.png)

**控制台日志输出截图:**

mirai正常,现在是无法启动
直接报错
**运行环境:**
 - 操作系统: 
 - `mirai-core` 版本: 2.7 M2
 - `mirai-api-http` 版本: 1.12.0
 - `graia-application-mirai` 版本: 0.20.1
 - 是否出现在机器人长期运行后: 否

graia-broadcast         0.11.1
graia-scheduler         0.0.5
 
**额外信息:**

**Comment by GMYXDS** [comment]
这个是咋解决的
