### ISSUE TITLE
报错 cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.event' 

### ISSUE THREAD

**Issue by LinHui88** [GraiaProject/Application#149]
**描述你遇到的问题:**
cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.event' 

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. ...uninstall graia,uninstall scheduler
2. ...pip install graia

**发生错误的代码**

![image](https://user-images.githubusercontent.com/40729083/125568831-f00f0255-3160-41a4-962d-6b98adffef10.png)

**控制台日志输出截图:**

mirai控制台没问题,graia压根没法启动
**运行环境:**
 - 操作系统:  ubuntu 
 - `mirai-core` 版本:  2.7 M2
 - `mirai-api-http` 版本:  0.12.0
 - `graia-application-mirai` 版本:  0.20.1
 - 是否出现在机器人长期运行后: 否

**额外信息:**

- `graia-broadcast  ` 版本: 0.11.3

**Comment by GreyElaina** [comment]
退版本. #147

**Comment by LinHui88** [comment]
感谢

**Comment by jupitersh** [comment]
现在适配的版本是什么
