### ISSUE TITLE
请问能不能具体说一下发本地图片的流程，试了很多方法都不能成功orz

### ISSUE THREAD

**Issue by Viottery** [GraiaProject/Application#15]
是我太菜了
版本是0.1.0

**Comment by GreyElaina** [comment]
我谔谔....

``` python
from graia.application.entry import Image, MessageChain

MessageChain.create([
    Image.fromLocalFile(...) # 你的文件名.
])

```

**Comment by Viottery** [comment]
> 我谔谔....
> 
> ```python
> from graia.application.entry import Image, MessageChain
> 
> MessageChain.create([
>     Image.fromLocalFile(...) # 你的文件名.
> ])
> ```
谢谢谢谢！没注意from local file...
