### ISSUE TITLE
问一下这个是什么问题

### ISSUE THREAD

**Issue by Yuanfeng123** [GraiaProject/Application#151]
![image](https://user-images.githubusercontent.com/61365068/126053748-18ddfddb-4066-4222-a497-0fbf207ca2a2.png)

**Comment by karakoo** [comment]
`graia.application.exceptions.AccountNotFound`
MCL没有登陆对应的QQ号
先仔细阅读文档，还有其他问题的话可以进群讨论

**Comment by Yuanfeng123** [comment]
嗯呢，我现在解决了，谢谢
