### ISSUE TITLE
安装graia-component-selector引起的主程序回退问题

### ISSUE THREAD

**Issue by Calvariaa** [GraiaProject/Application#16]
**描述你遇到的问题:**
ERROR: graia-component-selector 0.0.1 has requirement graia-application-mirai<0.0.6,>=0.0.5, but you'll have graia-application-mirai 0.1.1 which is incompatible.

**复现步骤:**
该 BUG 会在进行以下操作后出现:
pip install graia-component-selector

**控制台日志输出截图:**
^

**运行环境:**
 - 操作系统: Windows 10 x64
 - `mirai-core` 版本:1.3.0
 - `mirai-api-http` 版本:1.7.4
 - `graia-application-mirai` 版本:0.1.1 / 0.0.5?
 - 是否出现在机器人长期运行后: [是/否] 否

**额外信息:**
安装graia-component-selector的时候注意到自动把graia0.1.1的降级到了0.0.5 感觉有点奇怪所以过来提issue了

**Comment by GreyElaina** [comment]
![image](https://user-images.githubusercontent.com/31543961/89440124-c7ba9880-d77d-11ea-9982-ad93c2398976.png)
?

**Comment by GreyElaina** [comment]
很多包都有这个问题...我明天如果还活着就全部修了

**Comment by GreyElaina** [comment]
安装 `0.0.2` 版本以解决这个问题.

**Comment by Uwwal** [comment]
安装graia-template也会导致这个问题发生

**Comment by GreyElaina** [comment]
> 安装graia-template也会导致这个问题发生

垃圾poetry.

**Comment by GreyElaina** [comment]
已修复
