### ISSUE TITLE
Graia 实际上不兼容mirai-api-http 2.x (?

### ISSUE THREAD

**Issue by CberYellowstone** [GraiaProject/Application#166]
## 各包版本: 
`graia-application-mirai` : `0.20.1`
`graia-broadcast` : `0.11.4`  
> 实际上`graia-broadcast`有更新的版本`0.12.4`，
> 但是pip报告依赖版本为: `graia-application-mirai 0.20.1 requires graia-broadcast<0.12.0,>=0.11.0,`

`graia-saya` : `0.0.12`
> 矛盾的是，`graia-saya 0.0.12`依赖要求: `graia-broadcast<0.13.0,>=0.12.1`

`mirai-api-http` : `2.1.0`
`Python` : `3.8.11`

**因此导致`Graia`完全跑不起来**

---

## 具体表现:
>ImportError: cannot import name 'BaseDispatcher' from 'graia.broadcast.entities.event' (/usr/local/python38/lib/python3.8/site-packages/graia/broadcast/entities/event.py)

报错详情为上述信息

---

## 更多

由于对`mirai-api-http 2.1.0`的支持是在`graia-application-mirai 0.20.0`加入的

因此其他issue中的解决方法 *(指回退到`0.19.2`版本)* 并无实际作用，因为这会导致不适配`mirai-api-http 2.x`

# 希望开发者能在下一个版本解决这些冲突

**Comment by GreyElaina** [comment]
"下一个版本"
没有了, 欢迎 Avilla.

**Comment by GreyElaina** [comment]
the long answer, maybe it's what you want:

mirai-api-http 因为其主导开发者 royii 佛系维护, 各种意义上都**完全**与他本应该拥有的背道而驰,
以此, 我不觉得 graia 需要兼容这样的上游, 并且 `miraijvm + mirai-console-loader + mirai-console + mirai-api-http` 从各种意义上都**完全**只是在添乱, mirai-console 生态简直比 graia 在没有 saya 那会各种插件平台满天飞还糟糕, 环境部署的复杂度和困难性就算是我也倍感不适.
v4 在各种意义上都开创了一个新领域, 特别是 bcc, 但即便如此, 我也仍然对 one sdk to one platform 感到一丝不爽,
所以我给他翻篇了.
就是这样, 我会给 Avilla 的文档贡献很多(大概是 v3 时期的级别), 并且 Avilla Protocol 与 Avilla for OneBot 已经趋近完善,
众多 API 在我研究 telegram 时都不会有大的改动.
想要无缝切换平台? 期待未来吧.
