### ISSUE TITLE
图片发送没有成功

### ISSUE THREAD

**Issue by RF-Tar-Railt** [GraiaProject/Application#169]
**描述你遇到的问题:**

在bot和mcl中都显示已经将图片从本地发送，但是在qq里并未显示有图片发送出来

**发生错误的代码**

    if is_app_close is False and msg in this_dict:
        if 'http' in this_dict[msg]:
            await app.sendGroupMessage(group, MessageChain.create([Image.fromNetworkAddress(this_dict[msg])]))
        else:
            await app.sendGroupMessage(group, MessageChain.create([Plain(this_dict[msg])]))
**控制台日志输出截图:**

![图片](https://user-images.githubusercontent.com/42648639/132819908-fab19ade-d7d3-4f34-944f-f1dc9f1b43c7.png)

![屏幕截图 2021-09-10 142716](https://user-images.githubusercontent.com/42648639/132819224-8da0e246-8717-4735-ac5f-671fe3662016.png)

![屏幕截图 2021-09-10 142627](https://user-images.githubusercontent.com/42648639/132819240-f27a62d8-88f5-41f2-9923-5bb48e5c562b.png)

**运行环境:**
 - 操作系统:  windows10 家庭版
 - `mirai-core` 版本: 2.6.7
 - `mirai-api-http` 版本: 1.11.0
 - `graia-application-mirai` 版本: 0.18.4
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by Taokyla** [comment]
mirai 的问题，[链接](https://github.com/mamoe/mirai/issues/1536)

**Comment by RF-Tar-Railt** [comment]
mah更新到1.12.0，mirai-core版本更新到2.7.1-dev版本后可以正常发送图片了
girai换到0.19.2版本

**Comment by RF-Tar-Railt** [comment]
mah更新到1.12.0，mirai-core版本更新到2.7.1-dev版本后可以正常发送图片了
girai换到0.19.2版本
