### ISSUE TITLE
 发送带有At的消息时报错

### ISSUE THREAD

**Issue by Reacurt** [GraiaProject/Application#176]
**描述你遇到的问题:**
在发送带At的消息时，报错。mirai-console不会收到对应消息。

**复现步骤:**
机器人发送带有At的消息链都会报错。

**发生错误的代码**
`aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:1234/sendGroupMessage')`

**控制台日志输出截图:**
![image](https://user-images.githubusercontent.com/73050842/147563326-cff1a60d-7783-4c31-8053-8ed19b5c728a.png)
![image](https://user-images.githubusercontent.com/73050842/147563394-b73316f8-8094-4bbb-a3d0-bb0eb6f6a363.png)
![image](https://user-images.githubusercontent.com/73050842/147563425-402dcd7c-6387-40e1-a0dd-df249f2461e2.png)

**运行环境:**
 - 操作系统: win10 cmd
 - `mirai-core` 版本: v2.9.0
 - `mirai-api-http` 版本: v1.12.0
 - `graia-application-mirai` 版本: v0.19.2
 - `graia_broadcast`版本：v0.8.11
 - 是否出现在机器人长期运行后: 是

**额外信息:**

在使用旧版本mirai-core（v2.7.1）时该功能正常。
刚刚入门计算机，非常感谢您的工作，让我能体验到这么有趣的项目。虽然得知您的重心已经不再这个项目上，也恳请您指一条解决问题的大致方向。萌新感激不尽。

**Comment by Little-LinNian** [comment]
可以尝试https://github.com/GraiaProject/Ariadne

**Comment by Reacurt** [comment]
> 可以尝试https://github.com/GraiaProject/Ariadne

感谢指路，我去试一下
