### ISSUE TITLE
文档挂了

### ISSUE THREAD

**Issue by ryuujo1573** [GraiaProject/Application#178]
**描述你遇到的问题:**

- [x] 文档挂了，两个都挂了

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. ...
2. ...

**发生错误的代码**

**控制台日志输出截图:**

**运行环境:**
 - 操作系统: 
 - `mirai-core` 版本: 
 - `mirai-api-http` 版本: 
 - `graia-application-mirai` 版本: 
 - 是否出现在机器人长期运行后: 

**额外信息:**

**Comment by Little-LinNian** [comment]
see the #177
