### ISSUE TITLE
使用graia-component-selector终端报错

### ISSUE THREAD

**Issue by Uwwal** [GraiaProject/Application#18]
**描述你遇到的问题:**

使用graia-component-selector显示导入包错误
**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 导入component
![image](https://user-images.githubusercontent.com/69232066/89497577-34ba4680-d7ef-11ea-8e72-93bbd583c78c.png)

2. 运行报错
![image](https://user-images.githubusercontent.com/69232066/89497843-b611d900-d7ef-11ea-8513-3078c6a05dfa.png)

检查graia-application-mirai及graia-component-selector版本为最新
![image](https://user-images.githubusercontent.com/69232066/89497483-05a3d500-d7ef-11ea-9fc1-69f9f99c722a.png)

**运行环境:**
 - 操作系统: [例如: Android(Termux), Android(MiraiAndroid)]win10 64位
 - `mirai-core` 版本:1.3.0
 - `mirai-api-http` 版本:1.7.4
 - `graia-application-mirai` 版本:0.1.1
 - 是否出现在机器人长期运行后: [是/否] 否

**额外信息:**

**Comment by Uwwal** [comment]
顺便 刚刚更新的模板也会这样
![image](https://user-images.githubusercontent.com/69232066/89498483-e73ed900-d7f0-11ea-8f12-23c8b2cb3da3.png)

**Comment by GreyElaina** [comment]
= =看来还真只兼容0.0.5

**Comment by GreyElaina** [comment]
全部的扩展的 0.0.3 版本已经修复这个问题

> "3" 是个好数字.
