### ISSUE TITLE
请问如何获取好友/群聊列表

### ISSUE THREAD

**Issue by Uwwal** [GraiaProject/Application#19]
我的需求是在管理员在私聊发送拉黑指令之后 bot给被拉黑人发送一段消息.

不过我没法获取好友/群聊列表, 使用sendFriendMessage如果被拉黑人不是好友的话终端会报错.
我查看mirai-api-http管理相关是有这个方法的, 而后我在graia/application文件夹下文件并没有找到类似的方法.
谢谢!
(语序有点乱, 见谅...)

**Comment by GreyElaina** [comment]
`GraiaMiraiApplication.friendList`, `GraiaMiraiApplication.memberList`.

**Comment by GreyElaina** [comment]
如果你感兴趣, `GraiaMiraiApplication.getFriend`, `GraiaMiraiApplication.getMember`

**Comment by Uwwal** [comment]
> 如果你感兴趣, `GraiaMiraiApplication.getFriend`, `GraiaMiraiApplication.getMember`

感谢
