### ISSUE TITLE
群员被踢事件好像无法捕获

### ISSUE THREAD

**Issue by lindongbin** [GraiaProject/Application#2]
代码
@bcc.receiver("MemberLeaveEventKick")
async def member_leavekick(app: GraiaMiraiApplication, member: Member):
    print(member.id)

是不是写错了？日志也没有任何反应，事件换成退群的可以正常运行

另外想问下如何@群成员

代码
await app.sendGroupMessage(group, MessageChain.create([At(member.id), Plain("测试")]))

提示错误
File "pydantic/main.py", line 334, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)

**Comment by Chenwe-i-lin** [comment]
- 如果 mirai-api-http 不发事件, 我也没办法...
 - 在 0.0.5 版本中, 后一个BUG已经修复.
