### ISSUE TITLE
请问如何获取并发送临时会话消息？

### ISSUE THREAD

**Issue by OasisAkari** [GraiaProject/Application#20]
如题，我只找到了好友和群聊消息的方法，但是临时会话的似乎不太一样...
能给一个示例吗，谢谢

**Comment by GreyElaina** [comment]
``` python
from graia.application.event.messages import TempMessage

@bcc.receiver(TempMessage)
```

**Comment by OasisAkari** [comment]
> ```python
> from graia.application.event.messages import TempMessage
> 
> @bcc.receiver(TempMessage)
> ```


额...那么下面的应该怎么写呢，我尝试写成这样，但是测试的时候没有任何反应

```python
async def temp_message_handler(app: GraiaMiraiApplication, message: MessageChain, temp:TempMessage):
     if message.asDisplay() == '你好':
         msg = '你好'
         await app.sendTempMessage(temp,MessageChain.create(\
                     [Plain(msg)]).asSendable())

**Comment by GreyElaina** [comment]
您 确定 您 是 临时消息?

`print(message.asDisplay())` 看看输出吗, 或者判断前整个 `print(111)` 看看事件有没有被触发

**Comment by OasisAkari** [comment]
> 您 确定 您 是 临时消息?
> 
> `print(message.asDisplay())` 看看输出吗, 或者判断前整个 `print(111)` 看看事件有没有被触发

似乎没被触发。。

应该是临时消息吧，mirai的log里头写了个Temp
![image](https://user-images.githubusercontent.com/31803608/89611081-cb9a0800-d8ae-11ea-8189-42d71cc117f0.png)

**Comment by GreyElaina** [comment]
根据标准问题反馈模板重新提一个issue, 我来解决
