### ISSUE TITLE
是否实现了sendImageMessage发送图片功能呢？

### ISSUE THREAD

**Issue by apuded** [GraiaProject/Application#25]
查看了下模块代码，好像并没有实现sendImageMessage发送图片功能，使用文档中也没有提到这个功能点。求教！
但是发现一个uploadImage上传图片到服务器的功能，返回的是imageId等相关的信息（这个接口用途又是什么呢？）多谢！

**Comment by GreyElaina** [comment]
没有实现, 也没有必要.

作为 `Image` 底层的 `Shadow Element` 和 `Image Type Auto Transfer` 机制, 可以让开发者无需关注对图片本身的上传和结构分析.
`GraiaMiraiApplication.uploadImage` 方法作为与 `mirai-api-http` 对接的机制, 返回作为内/外部态的消息组件 `Image`,
属于底层 API.

**Comment by GreyElaina** [comment]
sendImageMessage 完全不需要实现, 实现起来难度也很大(Friend Group Temp 都需要顾及),
而 Image 的强大使其完全不需要被实现.

**Comment by apuded** [comment]
> 没有实现, 也没有必要.
> 
> 作为 `Image` 底层的 `Shadow Element` 和 `Image Type Auto Transfer` 机制, 可以让开发者无需关注对图片本身的上传和结构分析.
> `GraiaMiraiApplication.uploadImage` 方法作为与 `mirai-api-http` 对接的机制, 返回作为内/外部态的消息组件 `Image`,
> 属于底层 API.

感谢指导，原来发图片这么简单。
 await app.sendGroupMessage(group,MessageChain(__root__=[
         Image().fromLocalFile('/home/test/1509817457.jpg')
     ]))
不翻源码 只看文档的话，确实感觉很多功能无从下手。如果能做一个完整的使用级DEMO 各种小白式的示例代码，相信能吸引更多用户使用这个项目。到目前为止，我使用到的功能已经都摸索清楚了，可以把酷Q项目切过来了使用了，感谢作者的付出。

**Comment by GreyElaina** [comment]
你觉得该怎么做? BCC内部各种特性完全没有讲到, application 内部的机制都没法一个一个掏出来讲

**Comment by apuded** [comment]
> 你觉得该怎么做? BCC内部各种特性完全没有讲到, application 内部的机制都没法一个一个掏出来讲
文档确实有些晦涩高大上，不过这个项目是我目前唯一能从网上找到的mirai-api-http相关的项目，省去了自己去对接mirai-api-http所花费的时间。不知道作者有没有相关的交流群之类的。如果有赞助的渠道本人也愿意适当赞助支持下作者。

**Comment by GreyElaina** [comment]
本项目不接受任何形式的赞助.
