### ISSUE TITLE
边缘情况的处理, 可能包含健康检查等.

### ISSUE THREAD

**Issue by haowen-li** [GraiaProject/Application#27]
**描述你遇到的问题:**

在实现文档中的快速上手和复读机器人时，无法触发好友或群聊消息事件

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 将文档中的代码复制到本地文件bot.py中，修改authKey和account
2. 安装mirai-api-http，指定与之前相同的authKey并运行MiraiOK
3. 在MiraiOK的命令行界面中能正常收到消息
4. 运行bot.py，直到event receiver running...之后无论是群聊还是好友消息都没有任何反应，在friend_message_listener中print也是无效
5. 收到过一条重命名群名称的事件 [2020-08-09 10:11:48,028][ERROR]: received a unknown event: GroupNameChangeEvent{'type': 'GroupNameChangeEvent', 'origin': ......后略。说明graia是能和mirai-api-http通信的吧

**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/48872922/89723067-ec8c6580-da34-11ea-8f63-f3a14f29d84d.png)
![image](https://user-images.githubusercontent.com/48872922/89723099-35441e80-da35-11ea-8cc5-cea7f8cd3f66.png)

**运行环境:**
 - 操作系统: Windows
 - `mirai-core` 版本: 1.1.3
 - `mirai-api-http` 版本: 1.7.4
 - `graia-application-mirai` 版本: 0.1.5
 - 是否出现在机器人长期运行后: 否

原来mirai的一键包无法下载了，我借用了其他人分享的整合包，并删掉了无关插件，或许是其中某一步删多了？
谢谢~

**Comment by GreyElaina** [comment]
mirai-api-http 经常会出现这种事件不传递的问题....
关于 GroupNameChangeEvent: 我刚才测试了下, 没有你提到的这个问题, 无论是 0.1.5 还是现在正在开发的新版本.

**Comment by haowen-li** [comment]
> mirai-api-http 经常会出现这种事件不传递的问题....
> 关于 GroupNameChangeEvent: 我刚才测试了下, 没有你提到的这个问题, 无论是 0.1.5 还是现在正在开发的新版本.

那请问怎么解决呢？现在完全无法使用，重启mirai或者graia都触发不了私聊和群聊消息事件，其他的还没测试

**Comment by aboutmydreams** [comment]
我也遇到了这个问题，目前是通过不断重启解决的，希望后期能有较好的解决方案

**Comment by haowen-li** [comment]
> 我也遇到了这个问题，目前是通过不断重启解决的，希望后期能有较好的解决方案

重启mirai吗？我已经重启过四五次了，因为我现在的账号好友和群聊较多，每次重启都要好几分钟才能正常显示收到的消息

**Comment by GreyElaina** [comment]
可能的解决方案: 移植 v3 中的 `edge_case_handler`

**Comment by GreyElaina** [comment]
这都鸽多久了。。。国庆写

**Comment by GreyElaina** [comment]
2020/11/28 1:38 实现本特性
