### ISSUE TITLE
QQ群中一些信息获取不到

### ISSUE THREAD

**Issue by apuded** [GraiaProject/Application#29]
QQ群中无法获取某个发言用户的以下资料：
nickname：QQ网名（非群名片）
level：群中等级（如：冒泡）
性别
年龄
地区

翻看了下源码和mirai-api-http文档，好像目前版本并不支持这些基本信息（原来在酷q中能获取到）。
如果说法有误，请纠正，谢谢。

**Comment by GreyElaina** [comment]
我看你在 mirai-api-http 也提了一个相同的 issue.
看看 README 讲了什么:

> 欢迎[提出聪明的问题](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md), 也请不要[像个弱智一样提问](https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways)

明知故问, 此事非我能单独解决之事.

**Comment by apuded** [comment]
> 我看你在 mirai-api-http 也提了一个相同的 issue.
> 看看 README 讲了什么:
> 
> > 欢迎[提出聪明的问题](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md), 也请不要[像个弱智一样提问](https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways)
> 
> 明知故问, 此事非我能单独解决之事.

这不是明知故问，是本着确认的目的，往往自以为事不是什么本事，结果和预想往往相反。

**Comment by GreyElaina** [comment]
> > 我看你在 mirai-api-http 也提了一个相同的 issue.
> > 看看 README 讲了什么:
> > > 欢迎[提出聪明的问题](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md), 也请不要[像个弱智一样提问](https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways)
> > 
> > 
> > 明知故问, 此事非我能单独解决之事.
> 
> 这不是明知故问，是本着确认的目的，往往自以为事不是什么本事，结果和预想往往相反。

如你在模块 `graia.application.group` 处见到的,  `Group`, `Member`, `GroupConfig`, `MemberInfo`, 都没有你需要的字段.
我刚才去查了下 `mirai-api-http` 和 `mirai-core` 的代码, 也没有你所需要的**任何**信息.
...你应该早就知道有这个回应的.

**Comment by GreyElaina** [comment]
如果你非常非常需要这些信息, 我更推荐你使用[这个机器人框架](https://xiaolz.cn)
