### ISSUE TITLE
无法发送闪照

### ISSUE THREAD

**Issue by ShiroDoMain** [GraiaProject/Application#32]
**描述你遇到的问题:**
无法发送闪照
**复现步骤:**
该 BUG 会在进行以下操作后出现:
发送闪照时程序出现异常并卡住

**控制台日志输出截图:**
mirai-console输出正常收到消息

[2020-08-15 18:52:28,083][INFO]: launching app...
[2020-08-15 18:52:28,325][INFO]: using pure websocket to receive event
[2020-08-15 18:52:28,326][INFO]: event reveiver running...
/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/graia/application/message/chain.py:155: RuntimeWarning: coroutine 'Image.fromLocalFile.<locals>._Image_Internal.toExternal.<locals>._flash_image_transfer' was never awaited
  result.append(await run_always_await(i.toExternal(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**运行环境:**
 - 操作系统: MacOS 10.15.6
 - `mirai-core` 版本: 0.29.1
 - `mirai-api-http` 版本: 1.7.2
 - `graia-application-mirai` 版本: 0.1.11
 - 是否出现在机器人长期运行后: 否

**额外信息:**
群组消息和好友消息都是一样的报错

**Comment by GreyElaina** [comment]
what's wrong with your markdown?

**Comment by GreyElaina** [comment]
调用send****Message的方法那段代码发过来
