### ISSUE TITLE
Graia发送图片失败

### ISSUE THREAD

**Issue by baka-gourd** [GraiaProject/Application#33]
**描述你遇到的问题:**
graia发送图片失败

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 使用`Image.fromLocalFile`指定图片路径
2. 发送图片

**控制台日志输出截图:**

console：
![image](https://user-images.githubusercontent.com/36119339/90523389-6643f200-e19f-11ea-98be-5adcbe7de606.png)
graia：
`[2020-08-18 22:07:52,182][INFO]: [BOT *****] Group(*****) <- [mirai:image:{1633C2F2-9DF3-1B70-2C24-86D1646BB55B}.mirai]`

**运行环境:**
 - 操作系统: Windows10
 - `mirai-core` 版本: mirai-core-qqandroid-1.1.3
 - `mirai-api-http` 版本: mirai-api-http-v1.7.2
 - `graia-application-mirai` 版本: 0.1.13
 - 是否出现在机器人长期运行后: 否

**额外信息:**

![image](https://user-images.githubusercontent.com/36119339/90523961-1285d880-e1a0-11ea-9d2c-c247cc6fae5e.png)

**Comment by GreyElaina** [comment]
调的哪个方法?
 - `sendGroupMessage`
 - `sendTempMessage`
 - `sendFriendMessage`

**Comment by baka-gourd** [comment]
```python
img = Image.fromLocalFile("D:/Files/wallpaper.jpg")
await self.sendGroupMessage(group, MessageChain.create([img]))
```
事sendGroupMessage

**Comment by CaraJ7** [comment]
同样出现了这个问题，有些图片发出去可以打开但有些不能。

**Comment by GreyElaina** [comment]
> 同样出现了这个问题，有些图片发出去可以打开但有些不能。

为 mirai-api-http 问题.
