### ISSUE TITLE
是否可以返回At对象的禁言状态

### ISSUE THREAD

**Issue by windirt** [GraiaProject/Application#35]
正在写的小项目有一个需求，在执行一个命令之前查询 @对象是否被禁言，如已被禁言就不执行。
如果能够返回 At对象 ismuted 的布尔就好了

**Comment by jinzhijie** [comment]
目前的 Graia 好像还是按照 mirai-http-api 来做的，要是能实现你这种需求倒好了，我觉得你应该自己来实现一个（（（我个人看法

**Comment by GreyElaina** [comment]
不能, 参见 mirai-api-http 实现, 因为原作者已经基本不更新该项目, 而我本人也因为学业问题被迫停止更新, 你们可以用 `Broadcast Control` 和 `jpype` 实现一个用跨线程技术访问 mirai-core 的技术栈, 我最近正在手写本模块的文档.
