### ISSUE TITLE
使用getfriend出现问题

### ISSUE THREAD

**Issue by Viottery** [GraiaProject/Application#36]
**描述你遇到的问题:**
在调用getfriend后，返回了一个coroutine对象，无法放入send friend message中

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. ...调用getFriend函数放入sendFriendMessage
2. ...

**发生错误的代码**

await app.sendFriendMessage(app.getFriend(*******), MessageChain(__root__=[
                            Plain("test")
                        ]))
**控制台日志输出截图:**

**运行环境:**
 - 操作系统: win10
 - `mirai-core` 版本: 
 - `mirai-api-http` 版本: 
 - `graia-application-mirai` 版本: 
 - 是否出现在机器人长期运行后: 
否
**额外信息:**

**Comment by GreyElaina** [comment]
抱歉我不解答这个脑瘫问题, 您去csdn或者去读我的文档/python docs/pep484也比在这开issue等回复来的快.
