### ISSUE TITLE
尝试发送闪图时报错

### ISSUE THREAD

**Issue by eleanoryeung** [GraiaProject/Application#38]
**描述你遇到的问题:**
尝试发送闪图时报错

**复现步骤:**
该 BUG 会在进行以下操作后出现:
发送闪图

**发生错误的代码**
`await app.sendGroupMessage(group, MessageChain.create([Image.fromLocalFile(Path(path)).asFlash()]))`

**控制台日志输出截图:**
mirai-console控制台:
![Snipaste_2020-08-29_21-50-17](https://user-images.githubusercontent.com/7261604/91638375-cfe6ba80-ea41-11ea-8670-5bc4825e967b.png)
Graia控制台:
![Snipaste_2020-08-29_21-49-10](https://user-images.githubusercontent.com/7261604/91638385-d8d78c00-ea41-11ea-8686-ee90efe5cfcc.png)

**运行环境:**
 - 操作系统: CentOS 8
 - `mirai-core` 版本: mirai-core-qqandroid-1.1.3
 - `mirai-api-http` 版本: mirai-api-http-v1.7.4
 - `graia-application-mirai` 版本: 0.1.10
 - 是否出现在机器人长期运行后: 否（尝试添加新功能）

**额外信息:**
无

**Comment by GreyElaina** [comment]
用 try except 和 traceback.print_ext() 包住看看问题是什么

**Comment by eleanoryeung** [comment]
用新的commit里面的代码的话，它时而是闪图时而不是

**Comment by GreyElaina** [comment]
> 用新的commit里面的代码的话，它时而是闪图时而不是。普通图片反而会变成单独的闪照发送。

该问题已得到解决
