### ISSUE TITLE
利用定时任务发送本地图片报错

### ISSUE THREAD

**Issue by fmd12345** [GraiaProject/Application#39]
**描述你遇到的问题:**
我利用loop.create_task创建一个定时任务用来发送图片，但是会报错
exception=LookupError(<ContextVar name='application' at 0x03A23338>)>

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. loop.create_task 创建一个定时任务
2. 开始执行发送图片await app.sendGroupMessage(group,MessageChain.create([Image.fromLocalFile('1.jpg')])) 命令时

**发生错误的代码**

```python
app = GraiaMiraiApplication(..)
async def reminder():
    while True:
        await asyncio.sleep(1)
        if is_time():
            await app.sendGroupMessage(group,MessageChain.create([Image.fromLocalFile('1.jpg')]))
loop.create_task(reminder())
app.launch_blocking()
```

**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/5960842/92244564-ac19ed80-eef5-11ea-905e-fc52d1f0db90.png)
用的是miraiOK，没看到 mirai-console有什么输出

**运行环境:**
 - 操作系统: windows10
 - `mirai-core` 版本: mirai-core-qqandroid-1.1.3.jar
 - `mirai-api-http` 版本: mirai-api-http-v1.7.4.jar
 - `graia-application-mirai` 版本: 0.1.17
 - 是否出现在机器人长期运行后: 否

**额外信息:**

试了下发送文字消息是没问题的，不知道为什么发送图片时报错了，是我用法有问题吗？

**Comment by GreyElaina** [comment]
在上下文外发送消息...

使用这个:
``` python
from graia.application.context import enter_context

with enter_context(app=app): # 这里参数名我忘了, 你自己看看:
    await send.......

```

**Comment by fmd12345** [comment]
好的，非常感谢，我太菜了……
