### ISSUE TITLE
如何获取群消息的发送者的QQ号

### ISSUE THREAD

**Issue by RiotGamesU** [GraiaProject/Application#40]
实在是找不到方法

**Comment by YueDeYue** [comment]
member.id

**Comment by RiotGamesU** [comment]
> member.id

你好 可否细说 谢谢

@bcc.receiver(GroupMessage)
async def group_message_handler(app: GraiaMiraiApplication, message: MessageChain, group: gp.Group):
    print() # app, message, group的源码里都找不到对应的方法
