### ISSUE TITLE
scheduler报错

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Application#42]
**描述你遇到的问题:**
scheduler启动错误

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1.写个scheduler（使用crontab）
2.在规定时间报错

**发生错误的代码**
![Uploading S01005-122518(1)(1).jpg…]()

**控制台日志输出截图:**

**运行环境:**
 - 操作系统: Windows server 2016
 - `mirai-core` 版本: 1.3.0
 - `mirai-api-http` 版本: 1.8.2
 - `graia-application-mirai` 版本: 0.10.6
 - 是否出现在机器人长期运行后: 否

**额外信息:**

在以前的版本（忘记具体哪个版本）代码确认可以运行

**Comment by I-love-study** [comment]
日志
![S01004-230939(1)](https://user-images.githubusercontent.com/39652142/95040989-0336fc00-0708-11eb-9569-b4eaa3850202.jpg)

**Comment by GreyElaina** [comment]
#44
