### ISSUE TITLE
请问如何让机器人在群组中回复特定的人？

### ISSUE THREAD

**Issue by coranholmes** [GraiaProject/Application#43]
首先感谢大佬们提供mirai的python sdk，鞠躬……
我的需求是群里有人at了机器人之后，机器人可以通过回复（Quote）方式来回复该人（即构建如下图所示的一个`MessageChain`）。
![回复](https://user-images.githubusercontent.com/2607616/95081013-875ea300-074b-11eb-80f5-098afdc3e633.png)
目前做出了以下尝试和探索：
1. 我阅读了文档，发觉Quote元素不能被发送
2. 查看了`graia.application.message.elements.internal`里的Quote类也没有得到什么启发
3. 我不死心还去看了mirai别的sdk的文档，比如NodeMirai，发觉它有单独提供一个方法叫`sendQuotedGroupMessage`，但是目前本库没有这个方法。

我想请问目前的版本可以实现这个需求吗？不知道是不是我哪里看漏了，请大佬轻拍，(╥╯^╰╥)

**Comment by jinzhijie** [comment]
可以，用我的扩展库 `graiax-nem`，<https://nem.xiaojin233.cn/>，里面唯一的示例正好实现了这个功能

**Comment by I-love-study** [comment]
sendGroupMessage方法里面有quote参数，只需要像这样
`await app.sendGroupMessage(MessageChain, quote = message.get(Source)[0])`

**Comment by GreyElaina** [comment]
> 可以，用我的扩展库 `graiax-nem`，https://nem.xiaojin233.cn/，里面唯一的示例正好实现了这个功能
> 
> 当然我也会经常更新，不过由于学业原因可能不能经常更新。如果你在使用中发现了 bug，请在 https://github.com/jinzhijie/graiax-nem 汇报

注意你的行为: 在我看来, `graiax-nem` 还不够好, 虽然给出了非常大胆而直截了当的解决方案, 但在解决其他人问题时, 请优先介绍官方方案.

**Comment by coranholmes** [comment]
> 
> 
> sendGroupMessage方法里面有quote参数，只需要像这样
> `await app.sendGroupMessage(MessageChain, quote = message.get(Source)[0])`

感谢回复，但是我发觉这样quote的消息里会出现多余的at（如下图），怀疑和 #24 为关联问题，能麻烦大神reopen一下这两个issue看看吗？谢谢！
![double_at](https://user-images.githubusercontent.com/2607616/95657353-b2c80000-0b46-11eb-851c-635884276cdb.png)

**Comment by I-love-study** [comment]
> > sendGroupMessage方法里面有quote参数，只需要像这样
> > `await app.sendGroupMessage(MessageChain, quote = message.get(Source)[0])`
> 
> 感谢回复，但是我发觉这样quote的消息里会出现多余的at（如下图），怀疑和 #24 为关联问题，能麻烦大神reopen一下这两个issue看看吗？谢谢！
> ![double_at](https://user-images.githubusercontent.com/2607616/95657385-e3a83500-0b46-11eb-850e-79bb0b3e02c5.png)

这应该是你在引用已经引用其他消息的消息（说的有点绕）
这个不是graia的问题
应该上报到mirai(不知道那边是否有相关issue)
