### ISSUE TITLE
MessageChain拼接函数参数问题

### ISSUE THREAD

**Issue by NekodRider** [GraiaProject/Application#46]
**描述你遇到的问题:**
MessageChain 类的 plusWith 和 join 使用时候遇到 `TypeError: can only concatenate list (not "MessageChain") to list`
https://github.com/GraiaProject/Application/blob/6dba59798c8b5066424e1181a6f7ceeb047d815f/src/graia/application/message/chain.py#L206-L221 

**建议:**
不知道为啥三个方法只有 plus 方法写的是对的，是因为没返回值嘛233……
这里处理 chains 还是按照的 v3 的 MessageChain 类型，按照 v4 的 chains 应该传入 List[msg.\_\_root\_\_]
应该改成 `return self.create(sum([i.__root__ for i in chains], self.__root__))`

**Comment by GreyElaina** [comment]
考虑将 `__add__` 和 `__radd__` alias 到 `join` 上面.
