### ISSUE TITLE
[feature request] 更详细的文档

### ISSUE THREAD

**Issue by jinzhijie** [GraiaProject/Application#5]
能否在手册中对 `MessageChain` 中的 `has`, `get`, `join` 等函数做出一些讲解，我在使用中有很大的疑惑和不解 ~~（根本不会用）~~ .

**Comment by Chenwe-i-lin** [comment]
在写了

**Comment by Chenwe-i-lin** [comment]
写完了

**Comment by jinzhijie** [comment]
感谢！------------------&nbsp;Original&nbsp;------------------
