### ISSUE TITLE
Kanata匹配问题

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Application#52]
**描述你遇到的问题:**

使用Kanata的时候，当同时有FullMatch和RequireParam时，假如发送信息只能够匹配FullMatch，就会触发错误

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1.在bcc的dispatchers里填写 `Kanata([FullMatch('anime'), RequireParam(name = 'tag')])`
2.发送‘amine’

**发生错误的代码**

```
@bcc.receiver(GroupMessage, headless_decoraters = [Depend(judge.active_check_message)], dispatchers = [Kanata([FullMatch('anime'), RequireParam(name = 'tag')])])
async def anime(app: GraiaMiraiApplication, group: Group, message: MessageChain, member: Member, tag: MessageChain):
    ...
```

**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/39652142/97794405-8af32600-1c34-11eb-8325-954168f9833d.png)

**运行环境:**
 - 操作系统: Windows
 - `mirai-core` 版本: 1.0-M4
 - `mirai-api-http` 版本: 1.8.4
 - `graia-application-mirai` 版本: 0.10.11
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
老bug了.
