### ISSUE TITLE
当要发送的消息符合某些条件时，Graia处理缓慢且消息无法成功发出

### ISSUE THREAD

**Issue by Redlnn** [GraiaProject/Application#55]
**描述你遇到的问题:**
若准备在群里发出的内容超过130个字（一个汉字、全角符号、中文标点都算一个字），且同时包含至少6个汉字和至少5个标点符号（不管是中文的还是英文的）的时候，当程序运行到`sendGroupMessage()`，就会卡住3s左右之后再发送。然后虽然mirai的控制台显示出了要发送的消息的内容，但实际上消息并没有发出，在同一个群的成员看不到Bot发送的消息。但是在私聊中没有这种现象。

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 将代码复制到本地文件test.py中，修改authKey和account
2. 安装mirai-api-http，指定与之前相同的authKey并运行MiraiOK或mirai-console-loader
3. 运行test.py，直到 application has been initialized, used x.xxxs 之后，在该机器人qq加入的群中发送任意消息并留意python控制台与Mirai控制台

**发生错误的代码**
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import asyncio
from graia.application.entry import (GraiaMiraiApplication, Group, Friend, Member, MemberLeaveEventKick,
                                     MessageChain, Plain, Session)
from graia.broadcast import Broadcast

loop = asyncio.get_event_loop()

bcc = Broadcast(loop=loop)
app = GraiaMiraiApplication(
        broadcast=bcc,
        connect_info=Session(
                host='http://127.0.0.1:25567',  # 填入 httpapi 服务运行的地址
                authKey='mahuateng',  # 填入 authKey
                account=10001,  # 你的机器人的 qq 号
                websocket=True  # Graia 已经可以根据所配置的消息接收的方式来保证消息接收部分的正常运作.
        )
)

msg = '啊啊啊啊啊啊。。。。。111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'


@bcc.receiver('GroupMessage')
async def group_message_handler(group: Group, message: MessageChain, member: Member, app: GraiaMiraiApplication):
    print('---START---')
    await app.sendGroupMessage(group, MessageChain(__root__=[
        Plain(msg)
    ]))
    print('---STOP---')
    print(group)
    print(member)
    print(message)


@bcc.receiver('FriendMessage')
async def friend_message_handler(friend: Friend, app: GraiaMiraiApplication):
    print('---START---')
    await app.sendFriendMessage(friend, MessageChain(__root__=[
        Plain(msg)
    ]))
    print('---STOP---')
    print(friend)


app.launch_blocking()
```

**控制台日志输出截图:**
![Graia控制台](https://user-images.githubusercontent.com/41742767/98920057-97b42b80-250a-11eb-9f52-78d2a7107467.png)
![Mirai控制台](https://user-images.githubusercontent.com/41742767/98921719-94ba3a80-250c-11eb-9fe4-7e29fe4abdc6.png)
![Q群](https://user-images.githubusercontent.com/41742767/98920232-d1853200-250a-11eb-9744-61443900a069.png)

**运行环境（测试过的）:**
 - 操作系统: Windows10 20H2 64位
 - `mirai-core` 版本: 1.3.1
 - `mirai-api-http` 版本: v1.8.4（基于这一个[提交](https://github.com/project-mirai/mirai-api-http/commit/1f5dc543c96e8c7178a59475e6ff3896292ed13c)自己构建以用于新版本的`mirai-console`）
 - `mirai-console`和`mirai-console-terminal`版本: 1.0-RC-1
 - `graia-application-mirai` 版本: 0.10.13
 - 是否出现在机器人长期运行后: 否

**额外信息:**
之前使用 `Windows Server 2012 R2 64位` + `MiraiOK` + `mirai-core-1.2.3` + `mirai-api-http-1.8.4（官方发布版）` + `mirai-console-1.0-M4` 也有一样的问题，但是当时不是130个字，会多一点，没具体测试过  
  
这是我自己构建的[mirai-api-http-v1.8.4.jar.zip](https://github.com/GraiaProject/Application/files/5529526/mirai-api-http-v1.8.4.jar.zip)

**Comment by GreyElaina** [comment]
请开启 `debug` 模式以便我更好的追踪问题:

在实例化 Application 时传入 `debug=True`, 然后我看看...

**Comment by GreyElaina** [comment]
我怎么感觉是 `mirai-api-http` 的问题...

 - 你试试 timeit 下, 当你执行 `MessageChain.build` 这个协程方法所用的耗时, 我觉得应该不会太长;
 - 然后修改 `sendGroupMessage` 方法, 看看是不是 `mirai-api-http` 的堵塞

**Comment by GreyElaina** [comment]
怎么感觉是长消息的问题...你尝试过换账号吗?

**Comment by NekodRider** [comment]
同样代码我在 `ubuntu` 下试了下没有遇到这个问题，都基本零延迟，版本是 `MiraiOK` + `mirai-core-1.2.3` + `mirai-api-http-1.8.4` + `mirai-console-1.0-M4`

**Comment by GreyElaina** [comment]
恩...看来是 mirai 的问题, 我无法复现...

换个 issue 吧, 我想写下方便我和各位测试 graia 的 flags, 麻烦各位帮我提一下
