### ISSUE TITLE
Kanata对于含引用的消息的判断

### ISSUE THREAD

**Issue by xian18** [GraiaProject/Application#58]
**描述你遇到的问题:**

通过Kanata来获取（过滤）消息时，碰到带有引用 / 回复的消息时会自动跳过。
**复现步骤:**
该 BUG 会在进行以下操作后出现:
1.一个使用Kanata的函数
2.发送带有引用的，正常情况下能触发的一句话
3.然后发现应该触发的函数没有触发

**发生错误的代码**

```
@bcc.receiver("GroupMessage",dispatchers=[Kanata([ 
    RegexMatch(r'[\s]*#test:[\s]*'), 
    RequireParam(name="test") 
])]) 
async def test_func(app:GraiaMiraiApplication,test:MessageChain,event:GroupMessage):
    pass
```

**控制台日志输出截图:**

![mirai-console](https://user-images.githubusercontent.com/44394537/99149749-f1fbea80-26ca-11eb-8a06-e60c96654e82.jpg)
![graia](https://user-images.githubusercontent.com/44394537/99149765-063fe780-26cb-11eb-91f3-6589fed6bbe3.jpg)

**运行环境:**
 - 操作系统: Ubuntu 18.04
 - `mirai-core` 版本: mirai-console-1.0-M4.jar
 - `mirai-api-http` 版本: mirai-api-http-v1.8.3
 - `graia-application-mirai` 版本: 0.10.10
 - 是否出现在机器人长期运行后: 否

**额外信息:**

我个人认为是qq自动在引用消息后，正文前中额外添加了一个At

**Comment by GreyElaina** [comment]
~~窝草我回来怎么多了3个issue~~

会写的, 这个问题不大

**Comment by GreyElaina** [comment]
已经实现.

**Comment by jinzhijie** [comment]
此问题在 0.19.0 依然存在，咋办
