### ISSUE TITLE
Graia转换后的消息链缺失闪照元素

### ISSUE THREAD

**Issue by OasisAkari** [GraiaProject/Application#59]
**描述你遇到的问题:**
如题。

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 写一个能够接收消息的方法，并打印消息链
2. 在群内发送一张闪照
2. 可以发现mirai-console处还能看到闪照元素，但是Graia转换后的消息链中缺失了闪照

**发生错误的代码**
```python
@bcc.receiver("GroupMessage")
async def group_message_handler(app: GraiaMiraiApplication, message: MessageChain):
    print(message)
```
**控制台日志输出截图:**
![image](https://user-images.githubusercontent.com/31803608/99220882-7b6e0280-281a-11eb-8635-8f70ed023ab8.png)
![image](https://user-images.githubusercontent.com/31803608/99220907-8c1e7880-281a-11eb-9ae4-22483f5df241.png)

**运行环境:**
 - 操作系统: Windows 10
 - `mirai-core` 版本:  1.3.3
 - `mirai-api-http` 版本: 1.8.4
 - `graia-application-mirai` 版本: 0.10.14
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
看看 mirai-api-http 的返回, 一般来讲 graia 的消息链序列化非常的忠诚..

**Comment by OasisAkari** [comment]
> 看看 mirai-api-http 的返回, 一般来讲 graia 的消息链序列化非常的忠诚..

来自一位群友的截图，应该是有的
![image](https://user-images.githubusercontent.com/31803608/99267464-f0632b80-285e-11eb-99b1-14fd2aaab52e.png)

**Comment by I-love-study** [comment]
个人认为是因为[这里](https://github.com/GraiaProject/Application/blob/6c2854d24b084d613d82b85b0e618d2fa1852792/src/graia/application/message/elements/external.py#L14)FlashImage类没有继承ExternalElement
顺带一提发现因为instance在对比的时候会考虑到继承关系，所以但在message.get(Image)的时候，也会获得FlashImage
已[PR](https://github.com/GraiaProject/Application/pull/62)

**Comment by GreyElaina** [comment]
> 个人认为是因为[这里](https://github.com/GraiaProject/Application/blob/6c2854d24b084d613d82b85b0e618d2fa1852792/src/graia/application/message/elements/external.py#L14)FlashImage类没有继承ExternalElement
> 顺带一提发现因为instance在对比的时候会考虑到继承关系，所以但在message.get(Image)的时候，也会获得FlashImage
> 已[PR](https://github.com/GraiaProject/Application/pull/62)

请确认已经修复此 BUG, 没有也说一下

**Comment by I-love-study** [comment]
> > 个人认为是因为[这里](https://github.com/GraiaProject/Application/blob/6c2854d24b084d613d82b85b0e618d2fa1852792/src/graia/application/message/elements/external.py#L14)FlashImage类没有继承ExternalElement
> > 顺带一提发现因为instance在对比的时候会考虑到继承关系，所以但在message.get(Image)的时候，也会获得FlashImage
> > 已[PR](https://github.com/GraiaProject/Application/pull/62)
> 
> 请确认已经修复此 BUG, 没有也说一下

确认能接收到FlashImage并且message.get正常
