### ISSUE TITLE
行吧, 本项目不会停止更新, 别fork了

### ISSUE THREAD

**Issue by GreyElaina** [GraiaProject/Application#7]
晨风的机器人被tx封也可能只是因为他盈利过多(一个授权200+),
所以被搞了, 而cq因为风险太大才**主动**关闭的(是否是tx胁迫我暂且蒙在鼓里),
其他的看cq就直接关闭我觉得十分谔谔, 但我认为mirai仍然会转生的,
到目前看, mirai是本地协议, 实现的基本能用, 鉴于tx的协议自带向上兼容(qq2009改改都能用),
所以不需要跑, 要跑的话也没法逃了.

**Comment by jinzhijie** [comment]
吓死我，刚把 Mirai 全套家伙全 Fork 了一遍。。

**Comment by GreyElaina** [comment]
不过我想咕会, 玩游戏去

**Comment by GreyElaina** [comment]
然后就上线了一个版本.

**Comment by PainterPuppets** [comment]
大佬辛苦了。。未来还有可能会更新么

**Comment by GreyElaina** [comment]
> 大佬辛苦了。。未来还有可能会更新么

刚才不就更新了 0.1.0.

**Comment by jinzhijie** [comment]
所以说，Mirai 只是假跑路是吗？

**Comment by jinzhijie** [comment]
> > 大佬辛苦了。。未来还有可能会更新么
> 
> 刚才不就更新了 0.1.0.

好像没推倒 PyPI

**Comment by GreyElaina** [comment]
> 所以说，Mirai 只是假跑路是吗？

不确定, 你看到他们的样子了吧, 动荡岁月里面没有什么一定不一定的

**Comment by jinzhijie** [comment]
> > 所以说，Mirai 只是假跑路是吗？
> 
> 不确定, 你看到他们的样子了吧, 动荡岁月里面没有什么一定不一定的

说得也是，还是希望能继续。

**Comment by aboutmydreams** [comment]
辛苦大佬了

**Comment by GreyElaina** [comment]
# 对于一些问题的解释

> 这个问题出自 [这里](http://machbbs.com/hostloc/183772)

这个项目是 Graia Framework 的一部分. Graia Framework 是一款以 Python 为基础, 以类似 `mirai` 这样的聊天软件无头客户端实现驱动底层逻辑, 并在其基础上进行封装, 以更高的抽象程度来服务开发者及其应用的逻辑.

> 我可以单独使用这个项目吗?

**不行**. Graia Framework 即使未来可能有自己创造协议库的可能, 但现在的 Graia Application for Mirai(即你看到的这个项目) 乃至整个 Graia Framework 都是需要前置协议库支持的, 在 Graia Application for Mirai 这里则是需要 mirai, mirai-console 和 mirai-api-http 提供底层协议支持.

> 我可以以此攻击那些说 "QQ机器人完蛋啦, Github上的都是垃圾" 的吗?

**不行, 但最好也以委婉的方式劝阻他们不要这样做, 或者冷处理.**

**Comment by chenshenwei1998** [comment]
作者大大辛苦了，致敬！
