### ISSUE TITLE
[Kanata bug]RequireParam里面的参数包含FullMatch的数据

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Application#74]
**描述你遇到的问题:**

使用如下
```python
@bcc.receiver(GroupMessage,dispatchers = [Kanata([FullMatch('直播 '), RequireParam('tag')])])
```
当接收到消息"直播 Hanayori"的时候
`tag.asDisplay()`获取到的是"直播 Hanayori"而不是"Hanayori"
**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 创建一个Kanata，里面同时含有FullMatch和RequireParam
2. 运行

**发生错误的代码**

```python
@bcc.receiver(GroupMessage,dispatchers = [Kanata([FullMatch('直播 '), RequireParam('tag')])])
async def dd_watch(tag: MessageChain):
    name = tag.asDisplay().strip()
    print(name)
```
**控制台日志输出截图:**

**运行环境:**
 - 操作系统: Windows Server 2016
 - `mirai-core` 版本: 2.0-M1-1
 - `mirai-api-http` 版本: 1.9.2
 - `graia-application-mirai` 版本: 0.14.0
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
Kanata 修不动了, 工程量太大了。。

**Comment by I-love-study** [comment]
虽然说完全看不懂Kanata如何detect MessageChain的
但是在我打印Kanata中beforeDispatch的mapping_result时候
我发现他打印的是正确的
包括与在allocation后的参数都是对的

```python
mapping_result
{<Argument content=[RequireParam(name='tag', isGreed=False, checker=None, translator=None)]>: MessageChain(__root__=[Plain(type='Plain', text='Hanayori')])}
self.allocation(mapping_result)
{'tag': MessageChain(__root__=[Plain(type='Plain', text='Hanayori')])}
```

然后我还发现一件事情
就是我无论在`original_catch`函数里面字怎么写print都不会输出
怀疑有可能是`Dispatcher`完全没有运行`original_catch`
然后这个`tag`就成了event的`MessageChain`本身了
修起来应该不会太难
但是由于完全不知道Dispatcher怎么运作的
所以完全不会修。。。

**Comment by GreyElaina** [comment]
哦, 不是魔法处理的部分啊, 那可以修
