### ISSUE TITLE
mirai可以接收到信息,mirai-api-http + graia接收不到

### ISSUE THREAD

**Issue by RiotGamesU** [GraiaProject/Application#75]
windows server 2019 datacenter
mcl:1.3.3
console,terminal.core-all:2.0-M2
jdk:openjdk 15
mirai-api-http:1.9.2和1.9.3都试过
graia:latest

mirai可以接收到信息,但是graia接收不到

graia输出信息:
[2020-12-29 10:57:54,564][INFO]: initializing app...
[2020-12-29 10:57:54,632][INFO]: detecting remote's version...
[2020-12-29 10:57:54,680][INFO]: detected remote's version: 1.9.2
[2020-12-29 10:57:54,695][INFO]: using pure websocket to receive event
[2020-12-29 10:57:54,695][INFO]: event receive method checked.
[2020-12-29 10:57:54,695][INFO]: this application's initialization has been completed.
[2020-12-29 10:57:54,695][INFO]: --- setting start ---
[2020-12-29 10:57:54,695][INFO]: broadcast using: <graia.broadcast.Broadcast object at 0x00000236BC1D40D0>
[2020-12-29 10:57:54,695][INFO]: enable log of chat: yes
[2020-12-29 10:57:54,695][INFO]: debug: no
[2020-12-29 10:57:54,695][INFO]: version(remote): 1.9.2
[2020-12-29 10:57:54,695][INFO]: --- setting end ---
[2020-12-29 10:57:54,695][INFO]: application has been initialized, used 0.131s
[2020-12-29 10:57:54,695][INFO]: websocket daemon: websocket connection starting...
[2020-12-29 10:57:54,695][INFO]: websocket: connected

代码:
import asyncio

from graia.application import GraiaMiraiApplication, Session
from graia.broadcast import Broadcast

loop = asyncio.get_event_loop()
bcc = Broadcast(loop=loop)
app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host="http://localhost:8080",
        authKey="xxxx",
        account=xxxx,
        websocket=True
    )
)

代码没问题,稳定运行几个月了

**Comment by redjs** [comment]
我折腾了一个下午，终于hello,world了。
首先,java分oracle版和openjdk版，运行mirai-console-loader你需要使用openjdk版，不然就报上面的错。下载地址:http://jdk.java.net/java-se-ri/13
假如你想用graia，那你接着还需要下载1.9.0版本的mirai-api-http（这个是最新的稳定版)，下载完放plugins文件夹里。下载地址https://github.com/project-mirai/mirai-api-http/releases/tag/v1.9.0
这个稳定版的mirai-api-http插件依赖的是旧版mirai，mcl默认下载最新版mirai，所以你需要改mcl的配置文件(config.json)，这个配置文件和mcl.jar在同级目录下，你要把config.json改成:

{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "stable",
      "version": "1.1.0",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "stable",
      "version": "1.1.0",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "stable",
      "version": "1.3.3",
      "type": "libs"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}

接下来再重新运行mcl.jar，应该会自动下载并运行配置文件里指定的版本。
这个时候你再运行你的python代码试一试吧

**Comment by RiotGamesU** [comment]
> 我折腾了一个下午，终于hello,world了。
> 首先,java分oracle版和openjdk版，运行mirai-console-loader你需要使用openjdk版，不然就会报错。下载地址:http://jdk.java.net/java-se-ri/13
> 假如你想用graia，那你接着还需要下载1.9.0版本的mirai-api-http（这个是最新的稳定版)，下载完放plugins文件夹里。下载地址https://github.com/project-mirai/mirai-api-http/releases/tag/v1.9.0
> 这个稳定版的mirai-api-http插件依赖的是旧版mirai，mcl默认下载最新版mirai，所以你需要改mcl的配置文件(config.json)，这个配置文件和mcl.jar在同级目录下，你要把config.json改成:
> 
> {
> "js_optimization_level": -1,
> "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
> "maven_repo": "https://maven.aliyun.com/repository/public",
> "packages": [
> {
> "id": "net.mamoe:mirai-console",
> "channel": "stable",
> "version": "1.1.0",
> "type": "libs"
> },
> {
> "id": "net.mamoe:mirai-console-terminal",
> "channel": "stable",
> "version": "1.1.0",
> "type": "libs"
> },
> {
> "id": "net.mamoe:mirai-core-all",
> "channel": "stable",
> "version": "1.3.3",
> "type": "libs"
> }
> ],
> "disabled_scripts": [],
> "proxy": "",
> "log_level": 0,
> "script_props": {}
> }
> 
> 接下来再重新运行mcl.jar，应该会自动下载并运行配置文件里指定的版本。
> 这个时候你再运行你的python代码试一试吧

可以了,谢谢,我昨天也找到一种方法,mcl的配置文件里的版本全改成2.0-M1-1,mah用1.9.3也可以,但是截至目前发现的问题是获取不到at的昵称和发送at消息时不发at只发昵称,用你的这个方法可以正常发送at消息

**Comment by mtuba** [comment]
使用低版本的 mirai 登陆时会提示`net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)`
虽然用高版本的 mirai 可以登陆但是 graia 收不到消息...
