### ISSUE TITLE
第一步遇到问题

### ISSUE THREAD

**Issue by Viottery** [GraiaProject/Application#8]
pip导入库结束，运行，遇到如下问题
没有找到模块 graia.application.message
和g.a.friend（这里简写了）
找了下源代码确实没有，pip尝试更新也没用

**Comment by GreyElaina** [comment]
第一个改动出现了问题......换用 `graia.application.entry` 导入所有东西, 这是文档写错了

**Comment by GreyElaina** [comment]
还有, 你给我用Issue Template, 我刚才看了文档 没问题, 你的库是 `0.1.0` 版本吗?

**Comment by Viottery** [comment]
> 还有, 你给我用Issue Template, 我刚才看了文档 没问题, 你的库是 `0.1.0` 版本吗?

pip上下的0.0.6  用update也显示没有

**Comment by Viottery** [comment]
知道问题了，我再去试试，谢谢啦

**Comment by Viottery** [comment]
> 第一个改动出现了问题......换用 `graia.application.entry` 导入所有东西, 这是文档写错了

是把message和friend都换成entry吗，还是重新下一下这边的完整库

**Comment by GreyElaina** [comment]
> > 第一个改动出现了问题......换用 `graia.application.entry` 导入所有东西, 这是文档写错了
> 
> 是把message和friend都换成entry吗，还是重新下一下这边的完整库

使用版本为 `0.1.0` 的库

**Comment by Viottery** [comment]
> > 还有, 你给我用Issue Template, 我刚才看了文档 没问题, 你的库是 `0.1.0` 版本吗?
> 
> pip上下的0.0.6 用update也显示没有

可能用清华源的关系

**Comment by jinzhijie** [comment]
那问题来了，官方源的地址是啥？？（用惯阿里源了

**Comment by GreyElaina** [comment]
> 那问题来了，官方源的地址是啥？？（用惯阿里源了

爬去使用你聪明绝顶的搜索引擎.

**Comment by jinzhijie** [comment]
> > > 还有, 你给我用Issue Template, 我刚才看了文档 没问题, 你的库是 `0.1.0` 版本吗?
> > 
> > 
> > pip上下的0.0.6 用update也显示没有
> 
> 可能用清华源的关系

pip install -i https://pypi.python.org/simple graia-application-mirai==0.1.0
