### ISSUE TITLE
改善现有文档结构、内容

### ISSUE THREAD

**Issue by notnotype** [GraiaProject/Application#83]
现有文档内容不完全， 结构不合理， 有待改善。

**Comment by notnotype** [comment]
如有需要， 我可以帮助撰写文档

**Comment by Jerry-FaGe** [comment]
> 现有文档内容不完全， 结构不合理， 有待改善。

附议，现在的文档如果没有点开发基础其实很难读懂

**Comment by hyckleri** [comment]
> > 现有文档内容不完全， 结构不合理， 有待改善。
> 
> 附议，现在的文档如果没有点开发基础其实很难读懂
附附议，小白表示一脸懵

**Comment by wingxia** [comment]
> > 现有文档内容不完全， 结构不合理， 有待改善。
> 
> 附议，现在的文档如果没有点开发基础其实很难读懂

附议,小白还在专研中...

**Comment by GreyElaina** [comment]
摸了(?)

寒假了, 该写点了, 但如果基础没打好我就无能为力了

**Comment by GreyElaina** [comment]
https://graiaproject.github.io/Application

API 文档, 使用 `pdoc` 生成, 包括 `graia.broadcast` 的.

**Comment by Skybluevx** [comment]
> https://graiaproject.github.io/Application
> 
> API 文档, 使用 `pdoc` 生成, 包括 `graia.broadcast` 的.

这个打开是这样的
![image](https://user-images.githubusercontent.com/56282729/110231744-87f6a200-7f54-11eb-8a5d-829ce0ae93b8.png)

**Comment by GreyElaina** [comment]
帮忙写文档的人呢
