### ISSUE TITLE
[ERROR]: received a unknown event: FriendMessage

### ISSUE THREAD

**Issue by vayske** [GraiaProject/Application#86]
**描述你遇到的问题**

文档中的第一个例子无法实现

**发生错误的代码**

https://graia-document.vercel.app/docs/guides/installation
"历史性的第一次对话"中使用的代码，只修改了qq号和authKey

**控制台日志输出截图:**

![QQ截图20210131023507](https://user-images.githubusercontent.com/49426877/106381354-f56b4d80-636c-11eb-8ac6-de0fb0f18054.jpg)
![QQ截图20210131023235](https://user-images.githubusercontent.com/49426877/106381337-de2c6000-636c-11eb-825c-cf5ee3666482.jpg)
![QQ截图20210131023125](https://user-images.githubusercontent.com/49426877/106381339-e2587d80-636c-11eb-9d84-0b0bb2ecbbe8.jpg)

**运行环境:**
 - 操作系统:  Linux
 - `mirai-core` 版本:  "net.mamoe:mirai-core-all" version 2.2.1
 - `mirai-api-http` 版本:  "net.mamoe:mirai-api-http" version 1.9.7
 - `graia-application-mirai` 版本:  v0.15.2
 - 是否出现在机器人长期运行后:  否
 - 使用websocket协议

**额外信息:**

尝试过在friend_message_listener中加入print('hi')，没有成功print出来

**Comment by xiangxiangxiong9** [comment]
好家伙，我这是 [ERROR]: received a unknown event: GroupMessage 错误...

**Comment by xiangxiangxiong9** [comment]
先降级把...
pip uninstall graia-application-mirai
pip install graia-application-mirai==0.15.0

**Comment by vayske** [comment]
> 先降级把...
> pip uninstall graia-application-mirai
> pip install graia-application-mirai==0.15.0

降级之后可以用，暂时先这样了，非常感谢

**Comment by GreyElaina** [comment]
试试现在 git 上的版本

**Comment by xiangxiangxiong9** [comment]
> 试试现在 git 上的版本

那玩意咋用... poetry install 然后没有进pip freeze...

**Comment by xiangxiangxiong9** [comment]
> 试试现在 git 上的版本

似乎没有问题...

**Comment by JIACHENG135** [comment]
> 试试现在 git 上的版本

群主，请问您方便同意一下加群请求吗？
