### ISSUE TITLE
subclass of Element expected (type=type_error.subclass; expected_class=Element)

### ISSUE THREAD

**Issue by xian18** [GraiaProject/Application#87]
**描述你遇到的问题:**

MessageChain.create 不可用（？）
**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 运行下列代码

**发生错误的代码**

```
from graia.application.entry import MessageChain, Plain
MessageChain.create([Plain("1234")])
```
**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/44394537/106381811-6882bd00-6389-11eb-9259-c2076d953e1a.png)

**运行环境:**
 - 操作系统: Ubuntu 18.04.5 LTS
 - `graia-application-mirai` 版本 0.15.2

**Comment by GreyElaina** [comment]
马上修

**Comment by GreyElaina** [comment]
这类型系统用的真憋屈...
