### ISSUE TITLE
Message接收报错

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Application#88]
**描述你遇到的问题:**

接收消息会报错

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 打开graia
2. 发条消息

**发生错误的代码**

**控制台日志输出截图:**

![image](https://user-images.githubusercontent.com/39652142/106439321-813ac200-64b2-11eb-83f4-971da1c76fdb.png)
![image](https://user-images.githubusercontent.com/39652142/106439556-c9f27b00-64b2-11eb-8b87-ab2e000faa9a.png)

**运行环境:**
 - 操作系统: Windows 10
 - `mirai-core` 版本: 2.2.2
 - `mirai-api-http` 版本: 1.9.7
 - `graia-application-mirai` 版本: 0.15.3
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by hongxin-y** [comment]
同样的问题

- 操作系统: wsl
- `mirai-api-http` 版本: 1.9.6
- `graia-application-mirai` 版本: 0.15.2

**Comment by Minepig** [comment]
同样问题

- OS: Win 10
- `mirai-api-http`: 1.9.6
- `graia-application-mirai`: 0.15.3

**Comment by GreyElaina** [comment]
use 0.15.4
