### ISSUE TITLE
MessageChain.join() 无法正常使用

### ISSUE THREAD

**Issue by MakiseVon** [GraiaProject/Application#89]
**描述你遇到的问题:**

0.15.4 版本，使用 `MessageChain.join()` 会产生错误：`TypeError: can only concatenate list (not "tuple") to list`。
降回 0.14.1 版本后使用正常。

**复现步骤:**
该 BUG 会在进行以下操作后出现:

如上述。

**发生错误的代码**

调用 `MessageChain.join()`。

**控制台日志输出截图:**

![](https://i.loli.net/2021/02/02/V9dEB5KbZ7wigsc.png)

**运行环境:**
 - 操作系统: Android(MiraiAndroid)
 - `mirai-core` 版本: 2.2.2
 - `mirai-api-http` 版本: 1.9.6
 - `graia-application-mirai` 版本: 0.15.4
 - 是否出现在机器人长期运行后: 否

**额外信息:**

**Comment by GreyElaina** [comment]
`0.15.5`.
