### ISSUE TITLE
请问一下怎么获取最新历史聊天记录？

### ISSUE THREAD

**Issue by todest** [GraiaProject/Application#90]
我想做个判断是否复读的，然后不知道怎么获取历史聊天记录。

还有就是群聊memberList是获取不到机器人吗？而且找不到获取机器人群昵称的办法。

**Comment by macle-abc** [comment]
是否复读这个简单，你把聊条记录存数据库或者NoSql，然后自己判断就行

**Comment by todest** [comment]
> 是否复读这个简单，你把聊条记录存数据库或者NoSql，然后自己判断就行

只能这样吗？我看着有个app.fetchLatestMessage()和app.peekLatestMessage()不知道干啥的，我试着输出了，获取到的是空列表。

**Comment by GreyElaina** [comment]
没有方法, 自行组数据库判断.
