### ISSUE TITLE
无法接收引用消息

### ISSUE THREAD

**Issue by crab-in-the-northeast** [GraiaProject/Application#91]
**描述你遇到的问题:**
当在群里发送引用消息时，mirai端可以接受到引用消息，但graia的chat log没有显示。

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 在bot在的群里发送引用消息
2. （保证chat log打开）

**发生错误的代码**
```python3
from graia.broadcast import Broadcast
from graia.application import GraiaMiraiApplication, Session
from graia.application.message.chain import MessageChain
import asyncio

from graia.application.group import Group, Member

from time import sleep

loop = asyncio.get_event_loop()

bcc = Broadcast(loop=loop)

configs = get_config()

print(str(type(configs['settings']['tools']['MinecraftServerStatus']['CommandPrefix'])))
print(configs['settings']['tools']['MinecraftServerStatus']['CommandPrefix'])

app = GraiaMiraiApplication(
    broadcast=bcc,
    connect_info=Session(
        host=configs['miraiHttpApiHost'],
        authKey=configs['authKey'],
        account=configs['BotQQ'],
        WebSocket=True
    )
)


app.launch_blocking()

```

**控制台日志输出截图:**
graia端：
![Screen Capture_select-area_20210203190445](https://user-images.githubusercontent.com/46753037/106738394-d1e92100-6652-11eb-842f-5b75f879a27b.png)
mirai端：
![Screen Capture_select-area_20210203190413](https://user-images.githubusercontent.com/46753037/106738410-d7466b80-6652-11eb-9090-7a24a4ac6bd7.png)

如图，mirai端的这个引用回复消息，graia的chat log中没有显示。

**运行环境:**
 - 操作系统: graia端 UOS 5.4.50-amd64-desktop，mirai端 CentOS 7.6.1810(Py 2.7.5)
 - `mirai-core` 版本: 2.3.0
 - `mirai-api-http` 版本: 1.9.6
 - `graia-application-mirai` 版本: 0.15.5
 - 是否出现在机器人长期运行后: 否

**额外信息:**
无

**Comment by GreyElaina** [comment]
打开debug=True

**Comment by OasisAkari** [comment]
mirai-api-http 1.9.6存在引用消息不上报的问题，升级到1.9.7后此issue自然解决。

**Comment by GreyElaina** [comment]
> mirai-api-http 1.9.6存在引用消息不上报的问题，升级到1.9.7后此issue自然解决。

哦, 上游的问题, 事件这边几百年前就没改过了..

**Comment by crab-in-the-northeast** [comment]
https://github.com/project-mirai/mirai-api-http/issues/243
