### ISSUE TITLE
无法获取好友的备注信息？

### ISSUE THREAD

**Issue by finale-z** [GraiaProject/Application#97]
**描述你遇到的问题:**
使用 GraiaMiraiApplication.friendList(app) 获取到的好友列表里，所有的备注（remark）均为空

**复现步骤:**
该 BUG 会在进行以下操作后出现:
1. 使用GraiaMiraiApplication.friendList(app) 获取好友列表

**运行环境:**
 - 操作系统:  Armbian 21.02.1 Buster
 - `mirai-core` 版本:  2.4-RC
 - `mirai-api-http` 版本:  1.9.8
 - `graia-application-mirai` 版本:  
 - 是否出现在机器人长期运行后:  否

**Comment by GreyElaina** [comment]
请咨询 mirai-api-http 的维护者. 你大可打开 `debug=True` 然后看看我们亲爱的上游返回了什么玩意.
