### ISSUE TITLE
InterruptControl 模块已经没有了，但是文档里面还没有修改

### ISSUE THREAD

**Issue by Skybluevx** [GraiaProject/Application#99]
**描述你遇到的问题:**
`InterruptControl` 模块已经没有了，但是文档里面还没有修改；而且`from graia.application.interrupt` 已经变成 `from graia.application.interrupts` 了
![image](https://user-images.githubusercontent.com/56282729/110231631-e2433300-7f53-11eb-93e9-b51d156b2793.png)

**Comment by GreyElaina** [comment]
pr吧。

**Comment by GreyElaina** [comment]
这个文档要被废弃了。。我切到其他地方去
